### PR TITLE
Added CODEOWNERS files.

### LINKED ISSUE #32: Add codeowners file.
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
This is to add codeowners for different branches and also assign default reviewers based on the branching rules.

**Describe alternatives you've considered**
Na
**Additional context**
NA

### PR DESCRIPTION
**Pull request by sumanabhi**
This PR is going to add the CODEOWNERS file for this repo.

- [X] Basic CODEOWNERS file added
- [X] Still needed to add the Default reviewer for the two team.

Fixes #32

### CODE REVIEW

**Review by hadiyarajesh — COMMENTED** [review]
So, is it something like below?

1. Every user is codeowner of their respective branch
2. What about review request? How are we going to automatically request review?
3. What changes needs to be done to support it?

**Comment by sumanabhi** [comment]
> So, is it something like below?
> 
> 1. Every user is codeowner of their respective branch
> 2. What about review request? How are we going to automatically request review?
> 3. What changes needs to be done to support it?

Yeah @hadiyarajesh, Almost similar to this I have written to achieve it.
1. Not everyone than Just the members who are included in @NoteXCommunity/code-reviewer 
2. I have written to support all the changes but if this will not work we are having some options in the Repository Settings as well. if this does not work then we can look into that as well.

**Review by hadiyarajesh — APPROVED** [review]
Ok, thanks Let's see if it works.

**Comment by hadiyarajesh** [comment]
Can i merge now? Asking coz of don't-merge label

**Comment by sumanabhi** [comment]
> Can i merge now? Asking coz of don't-merge label

No, there are some branch not available till yesterday. Today will complete this. Then we can move ahead with merge.

**Comment by hadiyarajesh** [comment]
I like to address 2 things

1. Swapnil is not team lead, siddu patil is.
2. Loveleen is supposed to change her branch from loveleen_dev to branch_loveleen. @loveleenkaurnancy have you made the changes?

**Comment by hadiyarajesh** [comment]
I can see she did the changes. @sumanabhi can you please change both issues and then we're good to merge.

**Review by hadiyarajesh — APPROVED** [review]
LGTM, thanks

**Pull request merged**
