### PR TITLE
Updating .gitignore + Pull Request Template Files.

### PR DESCRIPTION
**Pull request by sumanabhi**
## 💡 Motivation, context, additional details, changes proposed

This PR is going to update the `.gitignore` file and also the Pull Request Template.

## ✏️ Checklist

- [X] **I've checked my code.**
- [X] **I've tested the change manually.**
- [ ] **I've invoked unit tests:** `./gradlew testStagingDebug testStagingDebugUnitTest`
- [ ] **I've invoked instrumentation tests:**

### CODE REVIEW

**Review by hadiyarajesh — APPROVED** [review]
Perfect. Thanks @sumanabhi

**Comment by hadiyarajesh** [comment]
Maybe GitHub has some issues. This build action run on PR and I also ran it manually now, but still, its status is not updating in PR. Maybe I'll need to deselect `Required status checks to pass before merging`

**Comment by hadiyarajesh** [comment]
Maybe GitHub has some issues. This build action run on PR and I also ran it manually now, but still, its status is not updating in PR. Maybe I'll need to deselect `Required status checks to pass before merging`

**Comment by sumanabhi** [comment]
> Maybe GitHub has some issues. This build action run on PR and I also ran it manually now, but still, its status is not updating in PR. Maybe I'll need to deselect `Required status checks to pass before merging`

Will look into this yml also.

**Pull request merged**
