### PR TITLE
Base Integration of Detekt Analytics tool done.

### PR DESCRIPTION
**Pull request by sumanabhi**
## 💡 Motivation, context, additional details, changes proposed

The motivation behind adding this PR is to enable the `pre-push` `git-hooks` for static analysis tools like `detekt` or `Ktlint`.

Q. Why are we keeping these to the local machine end rather than GitHub Actions?  
Ans:- as we all know, we are using the free GitHub Actions that come with a free runner with low bandwidth. So, as of now, we are trying to keep this on the local machine side only. Maybe in future if we find some other good option or some increased bandwidth from the side of the Github Free program.

- [X] Basic Detekt Plaugin enabled.
- [X] Detekt baseline configured for the whole Project.
- [X] Addition of the Detekt task to run as `pre-push` `git-hooks` is in Progress.
- [X] Ktlint enabled 
- [X] Addition of KtlintCheck task to run as `pre-push` `git-hooks`

Anyone can use the command to check locally as well from the terminal. 

**`./gradlew detekt`** or **`./gradlew ktlintCheck`**

Use this **`./gradlew ktlintFormat`** command for doing the formatting to `*.kt` file.

## ✏️ Checklist

- [X] **I've checked my code.**
- [X] **I've tested the change manually.**
- [X] **I've invoked unit tests:** `./gradlew detekt ktlintCheck --daemon --continue`
- [ ] **I've invoked instrumentation tests:**

### CODE REVIEW

**Comment by sumanabhi** [comment]
> ## 💡 Motivation, context, additional details, changes proposed
> The motivation behind adding this PR is to enable the `pre-push` `git-hooks` for static analysis tools like `detekt` or `Ktlint`.
> 
> Q. Why we are keeping these to the local machine end rather than GitHub Actions? Ans:- as we all know that we are using the free GitHub Actions that come with a free runner with low bandwidth. So, as of now, we are trying to keep this on the local machine side only. Maybe in future if we find some other good option or some increased bandwidth from the side of the Github Free program.
> 
> * [x]  Basic Detekt Plaugin enabled.
> * [x]  Detekt baseline configured for the whole Project.
> * [ ]  Addition of Detekt task to run as `pre-push` `git-hooks` is in Progress.
> * [ ]  Ktlint enabled
> * [ ]  Addition of Detekt task to run as `pre-push` `git-hooks`
> 
> ## ✏️ Checklist
> * [x]  **I've checked my code.**
> * [x]  **I've tested the change manually.**
> * [ ]  **I've invoked unit tests:** `./gradlew testStagingDebug testStagingDebugUnitTest`
> * [ ]  **I've invoked instrumentation tests:**
> 
> ## 📸 Reference Screenshots.

@hadiyarajesh I request you to kindly checkout this branch and verify in the `detekt.yml` files, that what other checks we can enable for this project to be assured for other Checks in the code in terms of standardisation.

feel free to ping me in case of any queries or addition into that.

**Comment by hadiyarajesh** [comment]
@sumanabhi thanks, sure I'll do the check. but wouldn't it be better if you create a PR for lead branch rather than `dev`? That will help us to track things properly.

**Comment by sumanabhi** [comment]
> @sumanabhi thanks, sure I'll do the check. but wouldn't it be better if you create a PR for the lead branch rather than `dev`? That will help us to track things properly.

I can. I raised this as this was the major change and needs to be merged ASAP. So that we can go ahead with the merge without any wait.

let me know If you want to move ahead with this. I will change it.

**Comment by hadiyarajesh** [comment]
I understand the urgency, but lets follow the pattern so we can keep the graph clean. you can tag your lead to merge this change asap after you merge it to their branch.

**Comment by sumanabhi** [comment]
> I understand the urgency, but let's follow the pattern so we can keep the graph clean. you can tag your lead to merge this change asap after you merge it to their branch.

I assigned this PR to @geetgobindsingh also as a reviewer. and also change the base branch from dev to his branch.

I am trying to cover the rest tasks by today or tomorrow EOD.

In the meantime, I request you guys to please checkout this branch and try running and testing this at your end.

**Pull request merged**
